MOUSEKEY_ENABLE = yes
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
# TAP_DANCE_ENABLE = yes
WPM_ENABLE = yes
OLED_DRIVER_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes

VIAL_INSECURE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes

# space reduction
QMK_SETTINGS = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no
